### ISSUE TITLE
Medication can be entered with duration/quantity of 0

### ISSUE THREAD

**Issue by kaphelps33** [kaphelps33/BGE#20]
**Describe the bug**
When a user enters a medication, they can enter absurd quantities such as 0 or 30,000.

**To Reproduce**
1. Go to add a new medication
2. In the dosage field enter any number
3. That number will be a valid one

**Expected behavior**
A user should not be able to enter a number 0 or below. A user also should not be able to enter crazy numbers, maybe above 90? There might be laws about the number that can be given. I know that for schedule 2 substances, you can't have more than 30 at a time, I believe.

**Comment by rushiljadia** [comment]
Limitations added.
