### ISSUE TITLE
Footer does not stick to the bottom of the page

### ISSUE THREAD

**Issue by kaphelps33** [kaphelps33/BGE#23]
The footer on the dashboard does not stick to the bottom of the page. There is a little margin below it.

**To Reproduce**
1. Go to Dashboard
2. Remove all medications
3. See error

**Expected behavior**
It should be at the very bottom of the page with no margin or space below it.

**Screenshots**
<img width="1723" alt="Screenshot 2024-11-14 at 3 10 54 PM" src="https://github.com/user-attachments/assets/e33623ad-94fc-493b-be46-6f59688a53c7">

**Comment by rushiljadia** [comment]
There seems to be a block saved for the footer specifically, seems like there are two layers of a footer, which is causing the spacing issue.
