### ISSUE TITLE
Price of medication does not display correctly

### ISSUE THREAD

**Issue by rushiljadia** [kaphelps33/BGE#29]
**Describe the bug**
When viewing any medication's price, either through the card view or through the info modal, the price only includes 1 decimal point. Ex: $20.0

**To Reproduce**
1. Log in to your account
2. Add a medicine with all necessary information 
3. Scroll down to card element of said medication

**Expected behavior**
The price should be displayed like this: $2.50.

**Screenshots**
<img width="303" alt="Screenshot 2024-11-20 at 2 04 19 AM" src="https://github.com/user-attachments/assets/03a843f0-776e-4503-ae17-8b138435d5d2">

**Comment by cdemarch** [comment]
medications display properly now: $xx.xx
